services:
  nats:
    image: nats:2.10-alpine
    container_name: transcendence-nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["--http_port=8222"]
    networks:
      - transcendence-network

  api-gateway:
    build:
      context: ./backend/services/gateway-service/
      target: production
    depends_on: [nats]
    env_file:
      - ./backend/services/gateway-service/.env
    networks:
      - transcendence-network

  frontend:
    build: ./backend/services/frontend-service/
    ports:
      - "3000:3000"
    restart: always

networks:
  transcendence-network:
    driver: bridge
