# This file is used to override or add some properties to docker-compose.yml.

services:
  auth:
    build:
      target: development     # use development stage in Dockerfile
    volumes:
      - ./services/auth:/app  # sync local folder to docker's /app folder
      - /app/node_modules     # don't sync node_modules

  frontend:
    build:
      target: development
    volumes:
      - ./services/frontend:/app
      - /app/node_modules
