# This file is used to override or add some properties to docker-compose.yml.

services:
  user-management:
    volumes:
      - ./shared:/app/shared
      - ./services/user-management/src:/app/services/user-management/src
    environment:
      - NODE_ENV=development
    command: npm run dev --workspaces

  frontend:
    volumes:
      - ./services/frontend/src:/app/services/frontend/src
    environment:
      - NODE_ENV=development
    command: npm run dev --workspaces
