# This file is used to override or add some properties to docker-compose.yml.

services:
  user-management:
    build:
      target: development
    environment:
      - NODE_ENV=development
    volumes:
      - ./shared:/app/shared
      - ./services/user-management/src:/app/services/user-management/src

  frontend:
    build:
      target: development
    environment:
      - NODE_ENV=development
    volumes:
      - ./shared:/app/shared
      - ./services/frontend/src:/app/services/frontend/src
      - ./services/frontend/public:/app/services/frontend/public
