# Notes:
# - Only caddy expose ports because it's the only entry point. It will then redirect requests to corresponding services (they are on the same Docker network)
# - All services need to communicate over HTTPS with caddy, so they must have the certs copied and configured in Fastify so they can trust caddy's TLS certificate.

services:
  # https://hub.docker.com/_/caddy#docker-compose-example
  caddy:
    image: caddy:2.10.2-alpine
    cap_add:
      - NET_ADMIN
    ports:
      - "8080:8080"
      - "8080:8080/udp"
    volumes:
      - ./caddy:/etc/caddy
      - ./secrets/certs/cert.pem:/certs/cert.pem:ro # ro = read-only
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      user-management:
        condition: service_healthy
      frontend:
        condition: service_healthy
      game:
        condition: service_healthy
    networks:
      - internal
    restart: unless-stopped

  nats:
    image: nats:2.10-alpine
    command: ["-T=false"] # Disable timestamps in logs
    networks:
      - internal
    restart: unless-stopped

  user-management:
    build:
      context: .
      dockerfile: ./services/user-management/Dockerfile
    depends_on:
      - nats
    networks:
      - internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-kf", "https://localhost:3000/health" ]
      interval: 5s
      timeout: 2s
      retries: 10

  frontend:
    build:
      context: .
      dockerfile: ./services/frontend/Dockerfile
    networks:
      - internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-kf", "https://localhost:3000/health" ]
      interval: 5s
      timeout: 2s
      retries: 10

  game:
    build:
      context: .
      dockerfile: ./services/game/Dockerfile
    depends_on:
      - nats
    networks:
      - internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-kf", "https://localhost:3000/health" ]
      interval: 5s
      timeout: 2s
      retries: 10

volumes:
  # Defining these volumes make them persistent across container restarts, so we
  # don't need to reclick "trust" on browser every time (they contains the TLS certs)
  caddy_data:
  caddy_config:

networks:
  internal:
    driver: bridge
