services:
  nats:
    image: nats:2.10-alpine
    networks:
      - app-network
    ports:
      - "4222:4222"
    restart: always

  auth:
    build: ./services/auth/
    networks:
      - app-network
    restart: always

  frontend:
    build: ./services/frontend/
    networks:
      - app-network
    ports:
      - "3000:3000"
    restart: always

  gateway:
    build: ./services/gateway/
    depends_on: [nats]
    env_file: ./services/gateway/.env
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
