# Notes:
# - Only caddy expose ports because it's the only entry point. It will then redirect requests to corresponding services (they are on the same Docker network)
# - All services need to communicate over HTTPS with caddy, so they must have the certs mounted and configured in Fastify so they can trust caddy's TLS certificate.

services:
  # https://hub.docker.com/_/caddy#docker-compose-example
  caddy:
    image: caddy:2.10.2-alpine
    cap_add:
      - NET_ADMIN
    ports:
      - "8080:8080"
      - "8080:8080/udp"
    volumes:
      - ./caddy:/etc/caddy
      - ./certs/cert.pem:/certs/cert.pem:ro # ro = read-only
      - ./certs/key.pem:/certs/key.pem:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - nats
      - user-management
      - frontend
      # Add services here
    networks:
      - internal
    restart: unless-stopped

  nats:
    image: nats:2.10-alpine
    networks:
      - internal
    restart: unless-stopped

  user-management:
    build: ./services/user-management/
    volumes:
      - ./certs:/certs:ro
      - ./services/user-management/.env:/app/.env:ro
    env_file:
      - ./services/user-management/.env
    depends_on: # TODO remove if not using nats
      - nats
    networks:
      - internal
    restart: unless-stopped

  frontend:
    build: ./services/frontend/
    volumes:
      - ./certs:/certs:ro
    networks:
      - internal
    restart: unless-stopped

volumes:
  # Defining these volumes make them persistent across container restarts, so we
  # don't need to reclick "trust" on browser every time (they contains the TLS certs)
  caddy_data:
  caddy_config:

networks:
  internal:
    driver: bridge
