# This file is used to override or add some properties to docker-compose.yml.

services:
  auth:
    command: npm run dev
    volumes:
      - ./services/auth:/app  # sync local folder to docker's /app folder
      - /app/node_modules     # don't sync node_modules

  frontend:
    command: npm run dev
    volumes:
      - ./services/frontend:/app
      - /app/node_modules

  gateway:
    command: npm run dev
    volumes:
      - ./services/gateway:/app
      - /app/node_modules
