# This file is used to override or add some properties to docker-compose.yml.

services:
  api-gateway:
    command: npm run dev
    volumes:
      - ./backend/services/gateway-service:/app # sync service folder to /app
      - /app/node_modules                     # don't sync node_modules

  frontend:
    command: npm run dev
    volumes:
      - ./backend/services/frontend-service:/app
      - /app/node_modules
