# Notes:
# - Only nginx expose ports because it's the only entry point. It will then redirect requests to corresponding services (they are on the same Docker network)
# - All services need to communicate over HTTPS with nginx, so they must have the certs copied and configured in Fastify so they can trust nginx's TLS certificate.

services:
  nginx:
    image: nginx:alpine3.23
    cap_add:
      - NET_ADMIN
    expose:
      - 8080
    environment:
      # For nginx-proxy
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=transcendence-42lyon.duckdns.org
      # For acme
      - LETSENCRYPT_HOST=transcendence-42lyon.duckdns.org
      - LETSENCRYPT_EMAIL=julien.grmd@gmail.com

      - HOSTNAME=${HOSTNAME:-localhost}
    volumes:
      - ./nginx:/etc/nginx:ro
      - ./secrets/certs:/certs:ro # ro = read-only
      - nginx_data:/data
      - nginx_config:/config
    depends_on:
      user-management:
        condition: service_healthy
      frontend:
        condition: service_healthy
      game:
        condition: service_healthy
    networks:
      - internal
      - nginx-proxy
    restart: unless-stopped

  nats:
    image: nats:2.10-alpine
    command: ["-T=false"] # Disable timestamps in logs
    networks:
      - internal
    restart: unless-stopped

  user-management:
    build:
      context: .
      dockerfile: ./services/user-management/Dockerfile
    depends_on:
      - nats
    volumes:
      - user_db:/app/data
    networks:
      - internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-kf", "https://localhost:3000/health" ]
      interval: 5s
      timeout: 2s
      retries: 10

  frontend:
    build:
      context: .
      dockerfile: ./services/frontend/Dockerfile
    networks:
      - internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-kf", "https://localhost:3000/health" ]
      interval: 5s
      timeout: 2s
      retries: 10

  game:
    build:
      context: .
      dockerfile: ./services/game/Dockerfile
    depends_on:
      - nats
    networks:
      - internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-kf", "https://localhost:3000/health" ]
      interval: 5s
      timeout: 2s
      retries: 10

volumes:
  # Defining these volumes make them persistent across container restarts, so we
  # don't need to reclick "trust" on browser every time (they contains the TLS certs)
  nginx_data:
  nginx_config:
  user_db:

networks:
  internal:
    driver: bridge
  nginx-proxy:
    external: true
