services:
  # Infrastructure
  nats:
    image: nats:2.10-alpine
    container_name: transcendence-nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["--http_port=8222"]
    networks:
      - transcendence-network

  # Applications (tes microservices)
  api-gateway:
    build:
      context: ./services/gateway-service
      dockerfile: Dockerfile
    depends_on: [nats]
    environment:
      - NATS_URL=nats://nats:4222
    networks:
      - transcendence-network


networks:
  transcendence-network:
    driver: bridge
